export const weatherTypes = {
    SET_INPUT: "SET_INPUT",
    SET_CITY_KEY: "SET_CITY_KEY",
    SET_CITY_NAME: "SET_CITY_NAME",
    GET_WEATHER_ICON: "GET_WEATHER_ICON",


    FETCH_AUTOCOMPLETE_SUCCESS: "FETCH_AUTOCOMPLETE_SUCCESS",
    FETCH_AUTOCOMPLETE_START: "FETCH_AUTOCOMPLETE_START",
    FETCH_AUTOCOMPLETE_ERROR: "FETCH_AUTOCOMPLETE_ERROR"
}