export const weatherTypes = {
    SET_INPUT: "SET_INPUT",
    SET_CITY_KEY: "SET_CITY_KEY",
    SET_CITY_NAME: "SET_CITY_NAME",
    GET_WEATHER_ICON: "GET_WEATHER_ICON",
    GET_AUTOCOMPLETE: "GET_AUTOCOMPLETE",

    ADD_FAVORITE: "ADD_FAVORITE",
    REMOVE_FAVORITE: "REMOVE_FAVORITE",
}