export const weatherTypes = {
    SET_INPUT: "SET_INPUT",
    SET_CITY_KEY: "SET_CITY_KEY",
    SET_CITY_NAME: "SET_CITY_NAME",
    GET_WEATHER_ICON: "GET_WEATHER_ICON",
    CLEAR_AUTOCOMPLETE: "CLEAR_AUTOCOMPLETE",

    FETCH_AUTOCOMPLETE_SUCCESS: "FETCH_AUTOCOMPLETE_SUCCESS",
    FETCH_START: "FETCH_START",
    FETCH_ERROR: "FETCH_ERROR",

    FETCH_WEATHER_SUCCESS: "FETCH_WEATHER_SUCCESS",
    FETCH_FORECAST_SUCCESS: "FETCH_FORECAST_SUCCESS",

    FETCH_GEO_LOCATION_START: "FETCH_GEO_LOCATION_START",
    FETCH_GEO_LOCATION_FAIL: 'FETCH_GEO_LOCATION_FAIL',
    FETCH_GEO_LOCATION_SUCCESS: "FETCH_GEO_LOCATION_SUCCESS",

    SET_ERROR: "SET_ERROR"
}