
export const favoriteTypes = {
    FETCH_FAVORITE: "FETCH_FAVORITE",
    FETCH_FAVORITE_START: "FETCH_FAVORITE_START",
    FETCH_FAVORITE_SUCCESS: "FETCH_FAVORITE_SUCCESS",
    FETCH_FAVORITE_FAIL: "FETCH_FAVORITE_FAIL",
    ADD_FAVORITE: "ADD_FAVORITE",
    REMOVE_FAVORITE: "REMOVE_FAVORITE",
}